# Generated by Django 5.1.1 on 2025-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tradingbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='access_token',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
